### ISSUE TITLE
Network unreachable exception for wiki bio

### ISSUE THREAD

**Issue by az0** [az0/entity-metadata#3]
````
Traceback (most recent call last):
  File "wikibio/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "wikibio/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "wikibio/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

````

**Comment by az0** [comment]
No longer using this code
